### ISSUE TITLE
wseek may not increase vmbuf capacity

### ISSUE THREAD

**Issue by ijz** [Adaptv/ribs2#10]
On line https://github.com/Adaptv/ribs2/blob/master/src/_vmbuf_impl.c#L55: 
```
if (vmb->write_loc == vmb->capacity)
```
Should it be this?
```
vmb->write_loc >= vmb->capacity
```
If I try and `wseek` beyond the capacity (https://github.com/Adaptv/ribs2/blob/master/src/_vmbuf_impl.c#L154), an `unsafe_wseek` could potentially make `write_loc` bigger than the capacity. Therefore, `resize_if_full` will not double the capacity. 
Or did I missed something obvious?

**Comment by ditmarus** [comment]
wseek  function is intended to skip part of the buffer that was already written directly (e.g. by regular memcpy)  and it can not be done if this space has not been already allocated, e.g. using resize_if_less. So in correct program flow wseek should never try to go beyond buffer capacity.
