### ISSUE TITLE
Asynchrounuous handling of requests

### ISSUE THREAD

**Issue by radcheb** [Adaptv/ribs2#7]
I’m trying to build a http server that connects to Redis database and retrieve some data to include in the http response. I am trying to increase throughput by using asynchronous Redis connection or a pipeline. However, this require to handle many http requests in the same time either by batching them for the pipeline or by saving the context of the current request and moving to another one  until we get response from the asynchronous Redis connection.
Is it possible to handle many contexts in the same time ?

**Comment by niryeffet** [comment]
Yes, ribs2 is asynchronous. The limit of the number of contexts is by memory and OS config (e.g. number of files descriptors in ulimit)
