### ISSUE TITLE
vmallocator_init checks mmap return value with incorrect variable

### ISSUE THREAD

**Issue by ssanke16** [Adaptv/ribs2#8]
mmap return value is checked with incorrect variable v->mem, instead it should be mem
in src/vmallocator.c:94
`
int vmallocator_init(struct vmallocator *v) 
{
if (v->mem) {
        vmallocator_reset(v);
        return 0;
    };
    v->fd = -1;
    v->capacity = VM_ALLOC_MIN_SIZE;
    void *mem = mmap(NULL, v->capacity, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (MAP_FAILED == mem)
        return LOGGER_PERROR("mmap"), -1; 
    v->mem = mem;
    v->wlocpos = 0;
    v->resize_func = _resize_buf;
    return 0;     
}
`

**Comment by erezarnon** [comment]
Fixed in https://github.com/TrueSkills/ribs2/, thank you.
